# Generated by Django 5.0.2 on 2024-02-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
